- name: get stable release
  shell: curl -sSL https://dl.k8s.io/release/stable.txt
  register: release

- name: install kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ release.stdout }}/bin/linux/{{ arch }}/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: +x

- name: mkdir ~/.kube
  file:
    path: ~/.kube
    state: directory

- name: prepare ~/.kube/config
  shell: 
    cmd: cp /etc/kubernetes/admin.conf ~/.kube/config

# TO DO : idempotency
- name: edit .bashrc
  shell: echo 'alias k=kubectl' >> ~/.bashrc && echo 'export KUBECONFIG=~/.kube/config' >> ~/.bashrc && . ~/.bashrc